### ISSUE TITLE
ValueError: Invalid children 'pattern' for svg-element <defs>.

### ISSUE THREAD

**Issue by joncutrer** [mozman/svgwrite#21]
I am attempting to recreate this SVG grid example in svgwrite

```xml
<svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <pattern id="smallGrid" width="8" height="8" patternUnits="userSpaceOnUse">
      <path d="M 8 0 L 0 0 0 8" fill="none" stroke="gray" stroke-width="0.5"/>
    </pattern>
    <pattern id="grid" width="80" height="80" patternUnits="userSpaceOnUse">
      <rect width="80" height="80" fill="url(#smallGrid)"/>
      <path d="M 80 0 L 0 0 0 80" fill="none" stroke="gray" stroke-width="1"/>
    </pattern>
  </defs>

  <rect width="100%" height="100%" fill="url(#grid)" />
</svg>
```

I am getting an error when attempting to add the patterns to the defs section.

Here is my code.

```python
import svgwrite
from svgwrite import pattern

dwg = svgwrite.Drawing('images/grid-patterns.svg', size=(u'100%', u'100%'), profile='tiny')

# <pattern id="smallGrid" width="8" height="8" patternUnits="userSpaceOnUse">
smallGrid = pattern.Pattern(size=(8, 8), patternUnits="userSpaceOnUse", id='smallGrid')

# <path d="M 8 0 L 0 0 0 8" fill="none" stroke="gray" stroke-width="0.5"/>
smallGrid.add( dwg.path(d="M 8 0 L 0 0 0 8", fill="none", stroke="gray", stroke_width="0.5"))

# debug
print(smallGrid.tostring())

# <pattern id="grid" width="80" height="80" patternUnits="userSpaceOnUse">
Grid = pattern.Pattern(size=(80, 80), patternUnits="userSpaceOnUse",id='grid')

# <rect width="80" height="80" fill="url(#smallGrid)"/>
Grid.add( dwg.rect(size=(80,80), fill="url(#smallGrid)"))

#<path d="M 80 0 L 0 0 0 80" fill="none" stroke="gray" stroke-width="1"/>
Grid.add( dwg.path(d="M 80 0 L 0 0 0 80", fill="none", stroke="gray", stroke_width="1"))

#debug
print(Grid.tostring())

# Add two patterns to defs
dwg.defs.add(smallGrid)
dwg.defs.add(Grid)

# <rect width="100%" height="100%" fill="url(#grid)" />
dwg.add(dwg.rect(size=("100%","100%"), fill="url(#grid)" ))

# write svg file to disk
dwg.save()
```

Here is the traceback

```shell
Traceback (most recent call last): 
...
  File "svg-grid-patterns.py", line 16, in <module>
    dwg.defs.add(smallGrid)
  File ".venv\lib\site-packages\svgwrite\base.py", line 173, in add
    self.validator.check_valid_children(self.elementname, element.elementname)
  File ".venv\lib\site-packages\svgwrite\validator2.py", line 135, in check_valid_children
    raise ValueError("Invalid children '%s' for svg-element <%s>." % (childrenname, elementname))
ValueError: Invalid children 'pattern' for svg-element <defs>.
```
I've also noticed that I cannot add the final rect without a specified x, y value.  Is that possible?

**Comment by DMRobertson** [comment]
When you create your `Drawing` you specify the `profile='tiny'` option. However, the [SVG Tiny 1.2 spec](https://www.w3.org/TR/SVGTiny12/expanded-toc.html) doesn't seem to define a `<pattern>` element at all! To get around this, you could try creating a fully-fledged SVG 1.1 with `profile='full'`, or disabling the validation checks by passing `debug=False` to [`Drawing.__init__()` ](http://svgwrite.readthedocs.io/en/latest/classes/drawing.html#svgwrite.drawing.Drawing.__init__).

For completeness, `svgwrite` seems to use [this data for SVG Full 1.1](https://github.com/mozman/svgwrite/blob/master/svgwrite/data/full11.py#L1070) and [this data for SVG Tiny 1.2](https://github.com/mozman/svgwrite/blob/master/svgwrite/data/tiny12.py#L775) to determine which elements may be children of `<defs>` elements.
