### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by FFY00** [mozman/svgwrite#61]
```
running test
running egg_info
creating svgwrite.egg-info
writing svgwrite.egg-info/PKG-INFO
writing dependency_links to svgwrite.egg-info/dependency_links.txt
writing requirements to svgwrite.egg-info/requires.txt
writing top-level names to svgwrite.egg-info/top_level.txt
writing manifest file 'svgwrite.egg-info/SOURCES.txt'
reading manifest file 'svgwrite.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'svgwrite.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    "Topic :: Software Development :: Libraries :: Python Modules",
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 229, in run
    self.run_tests()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 251, in run_tests
    exit=False,
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.7/unittest/loader.py", line 214, in loadTestsFromName
    raise TypeError("don't know how to make test from: %s" % obj)
TypeError: not all arguments converted during string formatting
```

**Comment by mozman** [comment]
Tests work on Windows 10 and on Manjaro Linux - tox run tests for py27, py37 and pypy3.

**Comment by nico202** [comment]
@FFY00 same error trying to build on guix, did you find out what's happening?
